package com.example.sharedcode.model;

/**
 * Created by jonathanlinford on 2/9/18.
 */

public enum UpdateType {
    LOBBY_LIST_UPDATED,
    PLAYER_LIST,
    GAME_STARTED,
    LOGIN_RESPONSE,
    LOGOUT_RESPONSE,
    GAME_CREATED,
    GAME_JOINED,
    GAME_LEFT,
    REGISTER_RESPONSE,
    //Chat
    CHAT_RECEIVED,
    CLAIMED_ROUTE, DREW_TRAIN_CARD, DISCARDED_TRAIN_CARD, DREW_DESTINATION_CARD, DISCARDED_DESTINATION_CARD, PLACED_TRAIN_CARS, HISTORY_UPDATED, NEW_PLAYER_TURN, PLAYER_JOINED, SERVER_DISCONNECT, GAME_INITIALIZED, TYPING_UPDATED, LAST_TURN, GAME_DONE, VICTORY_READY
}